<?php
include_once "Product.php";
$block = new Product();
var_dump($block->getData()[0]['img']);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/product.css">
    <title>php</title>
</head>
<body>
<div>
    <?php foreach ($block->getData() as $products):?>
    <?php var_dump($products);?>
    <div>
        <img src="<?php echo $products["img"] ?>" alt="<?php echo $products["title"]?>"/>
        <h2>
            <?php echo $products['title'];?>
        </h2>
        <?php for($i=0; $i<$products['rating']; $i++):?>
        +&nbsp;
        <?php endfor;?>
        <div class="price-wrapper">
            <?php if($products['price']['finalPrice'] == $products['price']['oldPrice']):?>
            <p style="font-weight: bold">
                <?= $products['price']["finalPrice"]?>
            </p>
            <?php else: ?>
            <p style="text-decoration: line-through">
                Old Price: <?= $products['price']['oldPrice'];?>
            </p>
            <p style="font-weight: bold">
                Final Price: <?= $products["price"]['finalPrice'];?>
            </p>
            <?php
                $sale = $products["price"]["oldPrice"] - $products["price"]["finalPrice"];
                $sale = $sale / ($products["price"]["oldPrice"] / 100);
                ?>
            <p style="color: red; font-weight: bold">
                Sale: <?= round($sale);?>
            </p>
            <?php endif?>
        </div>
    </div>
    <?php endforeach;?>
</div>

<div class="products-list">
    <?php for ($i = 0; $i < $block->getCountProduct(); $i++): ?>
    <div class="product-item">
        <div class="product-image">
            <img src="<?= $block->getImage($i);?>" alt="<?= $block->getTitle($i);?>">
        </div>
        <h2>
            <?= $block->getTitle($i);?>
        </h2>
        <div class="product-prices">
            <?php if ($block->isSalePrice($i)):?>
                <div>
                    Final price: <?= $block->getPrice($i)['finalPrice'];?> UAH
                </div>
                <div>
                    Old price: <?= $block->getPrice($i)['oldPrice'];?> UAH
                </div>
                <div>
                    Sale: <?= $block->getSale($i);?> %
                </div>
            <?php else:?>
                <div>
                    Final price: <?= $block->getPrice($i)['finalPrice'];?> UAH
                </div>
            <?php endif;?>
        </div>
        <?php if ($block->isActionProduct($i)):?>
            <div class="product-action">
                <?php if ($block->getActions($i)['bestsellers']):?>
                    <img src="./ima/product/bestsellers.png">
                <?php elseif ($block->getActions($i)['eco']):?>
                    <img src="./ima/product/eco.png">
                <?php elseif ($block->getActions($i)['new']):?>
                    <img src="./ima/product/new.png">
                <?php endif;?>
            </div>
        <?php endif;?>
        <div class="button">
            Buy now
        </div>
    </div>
    <?php endfor;?>
</div>
</body>
</html>