<?php
include_once './php/Product.php';
$block = new Product();
?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
<div class="wrapper">
    <?php foreach ($block->getData() as $key => $products): ?>
        <div class="card-wrap">
            <img src="<?= $block->getImage($key) ?>" alt="photo" class="photo">
            <p class="title"><?= $block->getTitle($key) ?></p>
            <div class="rating-wrap">
                <span class="rating">Rating:</span>
                <?php $block->getShowRating($key) ?>
            </div>
            <div class="price-wrap">
                <span class="text">Old price:</span>
                <span class="price"><?= $block->getPrice($key)['oldPrice'] . ' UAH' ?></span>
                <?php if ($block->getPrice($key)['oldPrice'] > $block->getPrice($key)['finalPrice']): ?>
                    <span class="text">Final price:</span>
                    <span class="price"><?= $block->getPrice($key)['finalPrice'] . ' UAH' ?></span>
                    <span class="text">discount:</span>
                    <span class="price discount"><?= $block->getDiscount($key) . ' UAH' ?></span>
                <?php endif; ?>
            </div>
            <a href="#" class="bottom">buy now</a>
        </div>
    <?php endforeach; ?>
</div>
</body>
</html>
