<?php
include_once "Product.php";
$block = new Product();
$name = 'Products list';
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Product list</title>
    <link rel="stylesheet" href="css/phtml.css">
</head>
<body>
<div class="product-list">
    <?php if($name): ?>
    <h1><?= $name; ?></h1>
    <?php endif; ?>
    <?php foreach ($block->getData() as $products): ?>
    <div class="product-gallery">
       <div class="product-item">
           <img src="<?= $products['img'] ?>" alt="" class="gal">
           <p class="item-title"><a href="#"><?= $products['title']; ?></a></p>
           <div class="action">
               <?php if ($products['actions']['bestsellers'] == true): ?>
                   <p class="action">Category: bestsellers</p>
               <?php endif; ?>
               <?php if ($products['actions']['eco'] == true): ?>
                   <p class="action">Category: eco</p>
               <?php endif; ?>
               <?php if ($products['actions']['new'] == true): ?>
                   <p class="action">Category: new</p>
               <?php endif; ?>
           </div>
           <div class="stars">
               <?php for ($i=0; $i<$products['rating']; $i++): ?>
                   <span style="color: gold">✩</span>
               <?php endfor; ?>
               <?php for ($i=0; $i<5-$products['rating']; $i++): ?>
                   <span>✩</span>
               <?php endfor; ?>
           </div>
            <div class="price order">
                <?php if ($products['price']['finalPrice'] == $products['price']['oldPrice']):?>
                    <p class="finalprice"><?= $products['price']['finalPrice']; ?> USD</p>
                <?php else: ?>
                    <p class="oldprice"><?= $products['price']['oldPrice']; ?></p>
                    <div class="discount" data-parent="Discount =>"><p>-<?= round(100 - ($products['price']['finalPrice'] / $products['price']['oldPrice'] * 100)); ?>%</p></div>
                    <p class="finalprice"><?= $products['price']['finalPrice']; ?> USD</p>
                <?php endif; ?>
            </div>
           <form class="order-now">
               <label for="submit" class="order"><a href="<?=$products['url'];?>"></a></label>
               <input type="submit" name="Order" value="Order" id="order">
           </form>
       </div>
    </div>
    <?php endforeach; ?>
</div>
</body>
</html>

