<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;

        }

        body {
            font-size: 15px;
            line-height: 1.20;
            font-family: sans-serif;
        }

        .wrapper {
            max-width: 1200px;
            margin: 0 auto;
            padding: 15px;
        }

        .produkt-list {
            list-style-type: none;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .product-item {
            width: 20%;
            padding: 15px;
            box-sizing: border-box;
        }

        .product-item * {
            margin-bottom: 10px;
        }

        .product-item .img {
            background-color: gray;
            width: 100%;
            padding-top: 60%;
        }

        .product-item .tittle {
            font-size: 18px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .rating {
            list-style-type: none;
            display: flex;
            justify-content: flex-start;
        }

        .rating > li {
            width: 20px;
            height: 20px;
            cursor: pointer;
            position: relative;
        }

        .rating > li > span {
            width: 20px;
            height: 20px;
            position: absolute;
            top: 0;
            left: 0;
            background-repeat: no-repeat;
            font-size: 20px;
            background-position: left;
            background-size: 20px;
        }

        .rating > li > span:first-of-type {
            background: url("star1.svg") no-repeat;
        }

        .rating > li > span:last-of-type {
            background: url("star.svg") no-repeat;
            width: 0;
            background-size: 20px;
        }
    </style>
</head>
<body>
<div class="wrapper">
    <ul class="produkt-list">
        <?php for ($i = 0; $i <= 20; $i++) : ?>
            <li class="product-item">
                <div class="img"></div>
                <h3 class="tittle">produckt tittle</h3>
                <ul class="rating">
                    <li>
                        <span></span>
                        <span></span>
                    </li>
                    <li>
                        <span></span>
                        <span></span>
                    </li>
                    <li>
                        <span></span>
                        <span></span>
                    </li>
                    <li>
                        <span></span>
                        <span></span>
                    </li>
                    <li>
                        <span></span>
                        <span></span>
                    </li>
                </ul>
                <p class="price">1200uah</p>
            </li>
        <?php endfor; ?>
    </ul>
</div>
<script>
    (function () {
            // function rating(ratingElem) {
            //     var count = 0,
            //         sum = 0,
            //         rating = 0;
            //     return function (e) {
            //
            //         console.log(e.target.parentNode, ratingElem);
            //         for (var i= 0; i < ratingElem.children.length; i++){
            //             if (e.target.parentNode === ratingElem.children[i]){
            //                 sum += i+1;
            //                 break;
            //             }
            //         }
            //         count++;
            //         rating = +(sum / count).toFixed(2);
            //
            //         for (var i = 0; i < ratingElem.children.length; i++){
            //             if (rating !== 0){
            //                 if (Math.ceil(rating) > i){
            //                     ratingElem.children[i].lastElementChild.style.width = (~~rating > i)? '100%' : Math.floor(rating % 1 * 100) + '%';
            //                 }
            //                 else{
            //                     ratingElem.children[i].lastElementChild.style.width = '0';
            //                 }
            //             }
            //         }
            //
            //     }
            // }

            // var ratings = document.querySelectorAll('.rating');
            //
            // for (var i = 0; i < ratings.length; i++) {
            //
            //     ratings[i].addEventListener('click', rating(ratings[i]));
            // }

            function Rating(ratingElem) {
                this.count = 0;
                this.sum = 0;
                this.rating = 0;
                this.ratingElem = ratingElem;
            }

            Rating.prototype.setSum = setSum;
            Rating.prototype.counter = counter;
            Rating.prototype.setRatingValue = setRatingValue;
            Rating.prototype.setRating = setRating;


            function setSum(e) {
                for (var i = 0; i < this.ratingElem.children.length; i++) {
                    if (e.target.parentNode === this.ratingElem.children[i]) {
                        this.sum += i + 1;
                        break;
                    }
                }
            }

            function counter() {
                this.count++;
                this.rating = +(this.sum / this.count).toFixed(2);
            }

            function setRatingValue() {
                for (var i = 0; i < this.ratingElem.children.length; i++) {

                    if (this.rating !== 0) {
                        if (Math.ceil(this.rating) > i) {
                            this.ratingElem.children[i].lastElementChild.style.width = (~~this.rating > i) ? '100%' : Math.floor(this.rating % 1 * 100) + '%';
                        } else {
                            this.ratingElem.children[i].lastElementChild.style.width = "0";
                        }
                    }

                }
            }

            function setRating(e) {
                this.setSum(e);
                this.counter();
                this.setRatingValue();
            }

            var ratings = document.querySelectorAll('.rating'), tmp;

            for (var i = 0; i < ratings.length; i++) {
                tmp = new Rating(ratings[i]);
                ratings[i].addEventListener('click', tmp.setRating.bind(tmp));
            }

        }
    )()
</script>
</body>
</html>