<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="css.css">
</head>
<body>
    <div class="wrapper">
        <ul class="product-list">
            <?php for($i=0; $i<20; $i++) :?>
            <li class="product-item">
                <div class="img"></div>
                <h3 class="title">Product Title</h3>
                <ul class="rating">
                    <li><span></span><span></span></li>
                    <li><span></span><span></span></li>
                    <li><span></span><span></span></li>
                    <li><span></span><span></span></li>
                    <li><span></span><span></span></li>
                </ul>
                <p class="prise">1200 UA</p>
            </li>
            <?php endfor; ?>
        </ul>
    </div>
<script src="java.js"></script>
</body>
</html>