<?php
include_once "Product.php";
$block = new Product();
$name = 'Product_list';
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="css/phtml.css">
</head>
<body>
<div class="product_list">
    <?php if ($name): ?>
        <h2><?= $name; ?></h2>
    <?php endif;?>
    <div class="product_wrapper">
        <?php foreach ($block->getData() as $products):  ?>
            <div class="product_item">
                <img src="<?php echo $products['img'] ?>" alt="">
                <div class="action-wrapper">
                    <?php if ($products['actions']['bestsellers'] == true): ?>
                        <p class="action">bestsellers</p>
                    <?php endif; ?>
                    <?php if ($products['actions']['eco'] == true): ?>
                        <p class="action">eco</p>
                    <?php endif; ?>
                    <?php if ($products['actions']['new'] == true): ?>
                        <p class="action">new</p>
                    <?php endif; ?>
                </div>
                <h3><?php echo $products['title'] ?></h3>
                <?php for ($i=0; $i<$products['rating']; $i++):?>
                    <span style="color: gold">*&nbsp</span>
                <?php endfor; ?>
                <?php for ($i=0; $i < 10 - $products['rating']; $i++):?>
                    <span>*&nbsp</span>
                <?php endfor; ?>
                <div class="cart-info">
                <div class="price_wrapper">
                    <?php if ($products['price']['finalPrice'] == $products['price']['oldPrice']):?>
                        <p class="price">Price: <?= $products['price']['finalPrice']?> UAH</p>
                    <?php else:?>
                        <?php
                        $sale = ($products['price']['oldPrice'] - $products['price']['finalPrice']) / ($products['price']['oldPrice'] / 100) ;
                        ?>
                        <span class="old-prce"><?= $products['price']['oldPrice'] ?> uah</span><br>
                        <span class="final-price"><?= $products['price']['finalPrice'] ?> uah</span>
                    <?php endif; ?>
                </div>
                <div class="buy">
                    <a href="<?=$products['url'];?>">Перейти</a>
                </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

</body>
</html>
